<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerIy0dqxu\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerIy0dqxu/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerIy0dqxu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIy0dqxu\appDevDebugProjectContainer();
