<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerC5ydtk0\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerC5ydtk0/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerC5ydtk0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerC5ydtk0\appDevDebugProjectContainer();
