<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\Container5k7o9ql\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/Container5k7o9ql/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\Container5k7o9ql\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container5k7o9ql\appDevDebugProjectContainer();
